version: '3.8'

services:
  # Redis service for rate limiting and chat history
  redis:
    image: redis:7-alpine
    container_name: ai-assistant-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-defaultpassword}
    networks:
      - ai-assistant-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Main AI Assistant Application (Backend)
  app:
    build: .
    container_name: ai-assistant-app
    restart: unless-stopped
    # Remove external port exposure - only accessed via nginx proxy
    expose:
      - "8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-defaultpassword}
      - ENVIRONMENT=production
      - CORS_ORIGINS=${CORS_ORIGINS:-https://yourdomain.com,https://www.yourdomain.com}
      - CORS_ALLOW_CREDENTIALS=${CORS_ALLOW_CREDENTIALS:-true}
    volumes:
      - ./service/chroma_persistent_storage:/app/service/chroma_persistent_storage
      - ./knowledge_base:/app/knowledge_base:ro
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - ai-assistant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Portfolio Application
  frontend:
    build: ./portfolio
    container_name: ai-assistant-frontend
    restart: unless-stopped
    ports:
      - "80:80"    # Expose frontend on port 80 for production
      - "443:443"  # HTTPS port for production
    volumes:
      - ./portfolio/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Mount SSL certificates
    depends_on:
      app:
        condition: service_healthy
    networks:
      - ai-assistant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  ai-assistant-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  redis_data:
    driver: local 